########################################
## Wallis product - Pi approximation
## Simple algorithm
########################################

from __future__ import division


## Pi 100 first decimals (generated by Wolfram Mathematica)
pi = 3.141592653589793238462643383279502884197169399375105820974944592307816406286208998628034825342117068

my_pi = 1

n = int(raw_input('How many product terms? '))

for i in range(1, n):
    my_pi *= 4* i ** 2 / (4 * i ** 2 - 1)

my_pi *=2

print pi
print my_pi
print abs(my_pi - pi)